build: Add missing models.h
 CC       drivers/gemaltomodem/radio-settings.o
../../drivers/gemaltomodem/radio-settings.c:43:10: fatal error: models.h: No such file or directory
   43 | #include "models.h"
      |          ^~~~~~~~~~